name: Deploy Laravel to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: ".,!.git,!.github,!node_modules,!.env,!storage/framework/sessions/*,!storage/framework/views/*,!storage/framework/cache/data/*,!storage/logs/*.log,!public/storage"
          target: ${{ secrets.VPS_DEPLOY_PATH }}
          strip_components: 0
          overwrite: true
      
      - name: Run deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            cd ${{ secrets.VPS_DEPLOY_PATH }}
            composer install --no-dev --optimize-autoloader --no-interaction
            npm install
            npm run build
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            # php artisan queue:restart